## DO NOT USE FOR LOOP IN THE ASSIGMENT WITH NUMPY

In [ ]:
# Numpy Array VS Python List

In [ ]:
l = [1, 2, 3, "Anant", True, 2.5] # Heterogenous
l

[1, 2, 3, 'Anant', True, 2.5]

In [ ]:
import numpy as np # np standard alias for numpy

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6]) # Homoegenous, same types of elements
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
l = [1, 2, 3, 4, 5]
l_by_3 = [i*3 for i in l] # multiply "every element" by 3, list comprehension
l_by_3

[3, 6, 9, 12, 15]

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a_by_3 = a*3 # multiply "every element" by 3
a_by_3 # Numpy has beautiful syntax for performing ELEMENT WISE OPERATIONS

array([ 3,  6,  9, 12, 15])

In [ ]:
l = range(1, 10000)
%timeit [i**2 for i in l] # element wise square

2.91 ms ± 47.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
a = np.array(range(1, 10000))
%timeit a**2 # [i**2 for i in a], imagine as if a is a single element

5.76 µs ± 140 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# Numpy Array Over Python List
# Better syntax for element wise operation
# Much much faster than list

In [ ]:
type(l_by_3)

list

In [ ]:
type(a_by_3) # N dimensional array

numpy.ndarray

In [ ]:
np.array([1, 2, 3, 4, 5]).ndim

1

In [ ]:
np.array([1, 2, 3, 4, 5]).shape # output will be a tuple

(5,)

In [ ]:
np.array([[1, 2, 3],
          [4, 5, 6],
          [10, 11, 12]]).ndim
# 3 rows, 3 columns
# list of multiple of 1D array, and each 1D array represents a row

2

In [ ]:
np.array([[1, 2, 3],
          [4, 5, 6],
          [10, 11, 12]]).shape # output will be tuple

(3, 3)

In [ ]:
np.array([[1, 2],
          [4, 5],
          [10, 11]]).shape

(3, 2)

In [ ]:
# 3D Numpy Array - Lecture-3
# L1 - 1D arrays
# L2 - 2D arrays
# L3 - 3D arrays

In [ ]:
np.array([[1, 2],
          [4, 5],
          [10]]) # every element has to have same number of element inside

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)
# ndim - in how many directions is the array growing
# shape - how many element present in outermost array, how many elemt in an element.....,,

1 (8,)


In [ ]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [ ]:
np.arange(1, 10, 2) # why call it arange and not range

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1, 10, 2.5) # provide decimal arguments as well

array([1. , 3.5, 6. , 8.5])

In [ ]:
list(range(1, 10, 2.5)) # range cannot take 

In [ ]:
np.array([1, 2, 3, 4]).dtype

dtype('int64')

In [ ]:
np.array([1, 2, 3.5, 4.0]) # Numpy only stores same type of data
# all the integers were raised to float

array([1. , 2. , 3.5, 4. ])

In [ ]:
np.array(["Harry Potter", 1, 2, 3]) # all the elements were raised to strings

array(['Harry Potter', '1', '2', '3'], dtype='<U21')

In [ ]:
np.array([1, 2, 3, 4], dtype="float")

array([1., 2., 3., 4.])

In [ ]:
np.array([1, 2, 3, 4], dtype="str")

array(['1', '2', '3', '4'], dtype='<U1')

In [ ]:
np.array(["Shivank", "Anant", "Ritwick"], dtype=float) # data type should match the values

In [ ]:
a = np.array([1, 2, 3.4, 7])
a.dtype, type(a)

(dtype('float64'), numpy.ndarray)

In [ ]:
a1 = np.arange(12)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# first element, second element,  last element - same as Python Lists
print(a1[0], a1[1], a1[-1])

0 1 11


In [ ]:
# additinally, in Numpy array, you can access multiple elements at the time
a1[[0, 1, -1]] # list of indexes, IMP the double [[]]

array([ 0,  1, 11])

In [ ]:
# Slicing

In [ ]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a1[:5]

array([0, 1, 2, 3, 4])

In [ ]:
a1[-5:-1], a1[-5:-1:1]

(array([ 7,  8,  9, 10]), array([ 7,  8,  9, 10]))

In [ ]:
a[-5:-1:-1] # start from -5, stop at -1 and go in neg direction

array([], dtype=float64)

In [ ]:
# Fancy Indexing

In [ ]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
a1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
a1[[0, 1, 2, 3, 4]]

array([1, 2, 3, 4, 5])

In [ ]:
a1[[ True,  True,  True,  True,  True, False, False, False, False,
       False]]

array([1, 2, 3, 4, 5])

In [ ]:
# For every instance of True, it will use the corresponding index
# Conversely, for every False, it will skip the corresponding index, and not print it.

In [ ]:
a1[a1 < 6] # Fancy Indexing - you index the array based on a condition

array([1, 2, 3, 4, 5])

In [ ]:
a1[a1 % 2 == 0] # does same job as filter

array([ 2,  4,  6,  8, 10])

In [ ]:
np.sum(a1)

55

In [ ]:
np.min(a1)

1

In [ ]:
np.max(a1)

10

In [ ]:
np.median(a1)

5.5

In [ ]:
np.mean(a1)

5.5

### AirBNB use case

https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

In [ ]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK # ! is for running a non Python command
# to use it no terminal, you will have download it

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 7.73MB/s]


In [ ]:
!ls

sample_data  survey.txt


In [ ]:
score = np.loadtxt("survey.txt", dtype="int")

In [ ]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
score.ndim

1

In [ ]:
total_responses = score.shape[0] # total number of responses
total_responses

1167

In [ ]:
np.min(score), score.min() # same result

(1, 1)

In [ ]:
np.max(score)

10

In [ ]:
np.mean(score), score.mean() # stick to style-1 so that reader is aware of Numpy array

(7.250214224507284, 7.250214224507284)

In [ ]:
# nps = %promoters - %detractors

In [ ]:
score <= 6 # detractors condition

array([False, False,  True, ...,  True, False, False])

In [ ]:
score >= 9  #promoters condition

array([False,  True, False, ..., False,  True,  True])

In [ ]:
# fancy indexing
n_promoters = len(score[score >= 9 ])
n_detracters = len(score[score <= 6])

In [ ]:
perc_promoters = (n_promoters/total_responses)*100
perc_detracters = (n_detracters/total_responses)*100
nps = perc_promoters - perc_detracters
print(nps)

23.73607540702657


#### Doubts

In [ ]:
a = np.array(["1", "2"])
a.astype("int")

array([1, 2])

In [ ]:
# !ls - list the items in my current working folder/directory